# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5ae433fc3c1e246be590845f1ae984d8831c5fa2ffb471775e3beca440a0223f5ce918ed5934415233a3b65640d538562c675d0f97806f8971879c5ab505df12

test:
  secret_key_base: 4de3ca2ff811bbd65446a5880240b0be3b65ad63dac29928e96ea1c153d19f1eeb865c74834e120d844fb2217814ad0a02132f4bf21eb6a096e892e6cb4e5fe3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
